apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "jet-helm-chart.labels" . | nindent 4 }}
  name: {{ include "jet-helm-chart.fullname" . }}-trace-aware-env
data:
  TRACE_AWARE_GRPC_SERVER_PORT: "80"

