apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectMan-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.projectMan-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.projectMan-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecret }}
      {{- if .imageCredentials }}
      imagePullSecrets:
        - name: {{ include "jet-helm-chart.fullname" $ }}-docker-registry-secret
      {{- else if .existImageSecrets }}
      imagePullSecrets:
        - name: {{ .existImageSecrets }}
      {{- end }}
      {{- end }}
      initContainers:
        - name: init-breeze-service
          image: busybox:1.28
          command: 
            - 'sh'
            - '-c'
            - 'until nslookup {{ include "jet-helm-chart.fullname" . }}-breeze.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for breeze; sleep 2; done'
        {{- if .Values.jetdb.enabled }}
        - name: init-project-man-db
          image: byzanteam/psql
          command:
            - 'sh'
            - '-c'
            - 'until psql -c "SELECT 1" "user=postgres password={{ .Values.jetdb.auth.postgresPassword }} dbname=project_man_prod host={{ .Values.jetdb.fullnameOverride }}"; do echo waiting for project man db; sleep 2; done'
        {{- end }}
      containers:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          image: {{ include "jet-helm-chart.projectMan-image" . }}
          imagePullPolicy: {{ .Values.projectMan.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-env
          ports:
            - name: {{ .Values.projectMan.service.name }}
              containerPort: {{ .Values.projectMan.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
