apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectMan-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.projectMan-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.projectMan-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecret }}
      {{- if .imageCredentials }}
      imagePullSecrets:
        - name: {{ include "jet-helm-chart.fullname" $ }}-docker-registry-secret
      {{- else if .existImageSecrets }}
      imagePullSecrets:
        - name: {{ .existImageSecrets }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          image: {{ include "jet-helm-chart.projectMan-image" . }}
          imagePullPolicy: {{ .Values.projectMan.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-env
          ports:
            - name: {{ .Values.projectMan.service.name }}
              containerPort: {{ .Values.projectMan.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
