apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectMan-labels" . | nindent 4 }}
spec:
  type: {{ .Values.projectMan.service.type }}
  ports:
    - port: {{ .Values.projectMan.service.port }}
      targetPort: {{ .Values.projectMan.service.name }}
      protocol: TCP
      name: {{ .Values.projectMan.service.name }}
  selector:
    {{- include "jet-helm-chart.projectMan-selectorLabels" . | nindent 4 }}
