apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "jet-helm-chart.labels" . | nindent 4 }}
  name: {{ include "jet-helm-chart.fullname" . }}-project-man-env
data:
  {{- .Values.projectMan.env | toYaml | nindent 2}}

