{{- if .Values.jetSubpath }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.jetSubpath }}
    forceSlash: true
{{- end }}
