remote: origin
target-branch: main
chart-dirs:
  - .
  - charts
charts:
  - .
namespace: default
release-label: app.kubernetes.io/namespace
helm-extra-set-args: "--set image.existingImageSecret=docker-registry-secret --set hosts[0]=localhost --set dynamicdb.enabled=true --set projectmandb.enabled=true"
additional-commands:
  - helm unittest --strict .
