remote: origin
target-branch: main
chart-dirs:
  - .
  - charts
charts:
  - .
namespace: default
release-label: app.kubernetes.io/namespace
helm-extra-args: "--set hosts[0]=localhost --set dynamicdb.enabled=true --set projectmandb.enabled=true --set image.existingImageSecret=docker-registry-secret"
additional-commands:
  - helm unittest --strict .
