apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectManLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.projectMan.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.projectManSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.projectManSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.existImageSecrets }}
      imagePullSecrets:
        - name: {{ .Values.existImageSecrets }}
      {{- end }}
      initContainers:
        - name: init-breeze-service
          image: busybox:1.28
          command: 
            - 'sh'
            - '-c'
            - 'until nslookup {{ include "jet-helm-chart.fullname" . }}-breeze.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for breeze; sleep 2; done'
        {{- if .Values.projectmandb.enabled }}
        - name: init-project-man-db
          image: byzanteam/psql
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret.name }}
                  key: project-man-password
          command:
            - 'sh'
            - '-c'
            - 'until psql -c "SELECT 1" "user=postgres dbname=project_man_prod host={{ .Values.projectmandb.fullnameOverride }}"; do echo waiting for project man db; sleep 2; done'
        {{- end }}
      containers:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          image: {{ include "jet-helm-chart.projectManImage" . }}
          imagePullPolicy: {{ .Values.projectMan.image.pullPolicy }}
          env:
            {{- range .Values.global.existingSecret.keys }}
            - name: {{ . | quote | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.existingSecret.name }}
                  key: {{ . | quote }}
            {{- end }}
            - name: DYNAMIC_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret.name }}
                  key: dynamicdb-password
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-project-man-env
          ports:
            - name: {{ .Values.projectMan.service.name }}
              containerPort: {{ .Values.projectMan.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.projectMan.resources | nindent 12 }}
      {{- with .Values.projectMan.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.projectMan.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.projectMan.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
