apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man-web
  labels:
    {{- include "jet-helm-chart.projectManLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{include "jet-helm-chart.rulePathPrefixs" (dict "jetPrefix" .Values.ingressroute.subpath "componentPrefix" "/jet") }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          port: 8080
      middlewares:
        {{- include "jet-helm-chart.webMiddlewares" . | nindent 8}}
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{include "jet-helm-chart.rulePathPrefixs" (dict "jetPrefix" .Values.ingressroute.subpath "componentPrefix" "/plugin") }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          port: 8090
      middlewares:
        {{- include "jet-helm-chart.webMiddlewares" . | nindent 8}}
---
{{- if .Values.certificate }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man-websecure
  labels:
    {{- include "jet-helm-chart.projectManLabels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{include "jet-helm-chart.rulePathPrefixs" (dict "jetPrefix" .Values.ingressroute.subpath "componentPrefix" "/jet") }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          port: 8080
      middlewares:
        {{- include "jet-helm-chart.websecureMiddlewares" . | nindent 8}}
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{include "jet-helm-chart.rulePathPrefixs" (dict "jetPrefix" .Values.ingressroute.subpath "componentPrefix" "/plugin") }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-project-man
          port: 8080
      middlewares:
        {{- include "jet-helm-chart.websecureMiddlewares" . | nindent 8}}
  tls:
    {{- if .Values.certificate.certResolver }}
    certResolver: {{ .Values.certificate.certResolver }}
    {{- else if .Values.certificate.tlsSecretName }}
    secretName: {{ .Values.certificate.tlsSecretName }}
    {{- end }}
{{- end }}
