apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectManLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: project-man
      protocol: TCP
      name: project-man
  selector:
    {{- include "jet-helm-chart.projectManSelectorLabels" . | nindent 4 }}
