apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-project-man
  labels:
    {{- include "jet-helm-chart.projectManLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: proj-man-grpc
      protocol: TCP
      name: proj-man-grpc
    - port: 80
      targetPort: proj-man-http
      protocol: TCP
      name: proj-man-http
  selector:
    {{- include "jet-helm-chart.projectManSelectorLabels" . | nindent 4 }}
