apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}
  labels:
    {{- include "jet-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "jet-helm-chart.fullname" . }}-docker-registry-secret
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "jet-helm-chart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-env
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
