apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-breeze
  labels:
    {{- include "jet-helm-chart.breezeLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.breeze.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.breezeSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.breezeSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.existImageSecrets }}
      imagePullSecrets:
        - name: {{ .Values.existImageSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-breeze
          image: {{ include "jet-helm-chart.breezeImage" . }}
          imagePullPolicy: {{ .Values.breeze.image.pullPolicy }}
          args:
            - 'start'
            - '-j'
            - 'http://{{ include "jet-helm-chart.fullname" . }}-project-man:{{ .Values.projectMan.service.port }}'
            - '-g'
            - '0.0.0.0:{{ .Values.breeze.service.port }}'
          env:
            - name: CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: credential_secret
            - name: DYNAMIC_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: dynamic_repo_password
            - name: JET_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: jet_jwt_private_key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: secret_key_base
            - name: TRACE_AWARE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: trace_aware_database_url
            - name: PROJECT_MAN_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "jet-helm-chart.fullname" . }}-env
                  key: project_man_database_url
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-breeze-env
          ports:
            - name: {{ .Values.breeze.service.name }}
              containerPort: {{ .Values.breeze.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.breeze.resources | nindent 12 }}
      {{- with .Values.breeze.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.breeze.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.breeze.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

