apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-breeze
  labels:
    {{- include "jet-helm-chart.breezeLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.breeze.replicaCount }}
  selector:
    matchLabels:
      {{- include "jet-helm-chart.breezeSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-helm-chart.breezeSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.existingImageSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.existingImageSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-breeze
          image: {{ include "jet-helm-chart.breezeImage" . }}
          imagePullPolicy: {{ .Values.breeze.image.pullPolicy }}
          args:
            - 'start'
            - '-j'
            - 'http://{{ include "jet-helm-chart.fullname" . }}-project-man:50051'
            - '-g'
            - '0.0.0.0:50052'
          env:
            {{- range .Values.global.existingSecret.keys }}
            - name: {{ . | quote | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.existingSecret.name }}
                  key: {{ . | quote }}
            {{- end }}
            - name: DYNAMIC_REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret.name }}
                  key: dynamicdb-password
          envFrom:
            - configMapRef:
                name: {{ include "jet-helm-chart.fullname" . }}-breeze-env
          ports:
            - name: breeze
              containerPort: 50052
              protocol: TCP
          resources:
            {{- toYaml .Values.breeze.resources | nindent 12 }}
      {{- with .Values.breeze.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.breeze.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.breeze.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

