apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-breeze-web
  labels:
    {{- include "jet-helm-chart.breezeLabels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{ printf "PathPrefix(`%s`)" (include "jet-helm-chart.buildPath" (dict "prefix" .Values.ingressroute.subpath "path" "/breeze")) }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-breeze
          port: {{ .Values.breeze.service.port }}
      middlewares:
        {{- include "jet-helm-chart.webMiddlewares" . | nindent 8}}
---
{{- if .Values.jetTLS }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-breeze-websecure
  labels:
    {{- include "jet-helm-chart.breezeLabels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "jet-helm-chart.ruleHosts" . }} && {{ printf "PathPrefix(`%s`)" (include "jet-helm-chart.buildPath" (dict "prefix" .Values.ingressroute.subpath "path" "/breeze")) }}
      kind: Rule
      services:
        - name: {{ include "jet-helm-chart.fullname" . }}-breeze
          port: {{ .Values.breeze.service.port }}
      middlewares:
        {{- include "jet-helm-chart.webMiddlewares" . | nindent 8}}
  tls:
    {{- if .Values.jetTLS.certResolver }}
    certResolver: {{ .Values.jetTLS.certResolver }}
    {{- else if .Values.jetTLS.tlsSecretName }}
    secretName: {{ .Values.jetTLS.tlsSecretName }}
    {{- end }}
{{- end }}
