apiVersion: v1
kind: Service
metadata:
  name: {{ include "jet-helm-chart.fullname" . }}-breeze
  labels:
    {{- include "jet-helm-chart.breezeLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50052
      targetPort: breeze
      protocol: TCP
      name: breeze
  selector:
    {{- include "jet-helm-chart.breezeSelectorLabels" . | nindent 4 }}
