name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: install helm unittest plugin
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest.git --version 0.2.8

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Install dependent environment
        run: |
          helm repo add traefik https://traefik.github.io/charts
          helm install traefik traefik/traefik

      - name: Run chart-testing (install)
        run: helm install jet . --dry-run
